apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /uno(/|$)(.*)
            backend:
              serviceName: backend-service
              servicePort: 3000
          - path: /dos(/|$)(.*)
            backend:
              serviceName: backend-service
              servicePort: 3001
          - path: /tres(/|$)(.*)
            backend:
              serviceName: backend-service
              servicePort: 3002
